services:
  app:
    build: ./app
    container_name: sysreport_app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    build: ./redis
    container_name: sysreport_redis
    ports:
      - "6379:6379"
  
  monitor:
    build: ./monitor
    container_name: sysreport_monitor
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
