timeout: 5000 # in milliseconds
hosts:
  totens:
    - localhost
    - ::1 
    - www.google.com
    - www.github.com
    - www.stackoverflow.com
    - www.reddit.com
  panels:
    - www.youtube.com
    - www.netflix.com
    - www.spotify.com
    - www.hulu.com
    - www.primevideo.com